export const properties = [
 {
    _id: 1,
    title: "Real House Luxury Villa",
    location: "Victoria Island, Lagos",
    bedrooms: 6,
    bathrooms: 3,
    price: "₦ 3,340,000,000",
    image: "https://res.cloudinary.com/ds0a0s3k3/image/upload/v1748388673/houseimage1_u0b5mm.png",
    featured: true,
    purpose: "Sale",
    type:"Bungalow",
  },
  {
    _id: 2,
    title: "Exquisite Haven Flat",
    location: "Festac, Lagos",
    bedrooms: 5,
    bathrooms: 3,
    price: "₦ 4,000,000/1 Year",
    image: "https://res.cloudinary.com/ds0a0s3k3/image/upload/v1748388674/houseimage2_biyoxb.png",
    featured: true,
    purpose: "Rent",
    type:"Flat",
  },
  {
    _id: 3,
    title: "Luxe Palatial Villa",
    location: "Banana Island, Lagos",
    bedrooms: 7,
    bathrooms: 3,
    price: "₦ 5,350,000,000",
    image: "https://res.cloudinary.com/ds0a0s3k3/image/upload/v1748388673/houseimage3_tdw8hm.png",
    featured: true,
    purpose: "Sale",
    type:"Contemporary",
  },

   {
    _id: 4,
    title: "Harmony Luxury Villa",
    location: "Mushin, Lagos",
    bedrooms: 4,
    bathrooms: 3,
    price: "₦ 4,000,000,000",
    image: "https://res.cloudinary.com/ds0a0s3k3/image/upload/v1748388674/houseimage4_rnhqr6.png",
    featured: true,
    purpose: "Sale",
    type:"Contemporary",
  },
  {
    _id: 5,
    title: "Real House Luxury Villa",
    location: "Victoria Island, Lagos",
    bedrooms: 6,
    bathrooms: 4,
    price: "₦ 350,000,000/1 Year",
    image: "https://res.cloudinary.com/ds0a0s3k3/image/upload/v1748388673/houseimage5_anqrfl.png",
    featured: true,
    purpose: "Rent",
    type:"Contemporary",
  },
  {
    _id: 6,
    title: "Real House Luxury Villa",
    location: "Lekki-Ajah, Lagos",
    bedrooms: 5,
    bathrooms: 3,
    price: "₦ 4,200,000,000",
    image: "https://res.cloudinary.com/ds0a0s3k3/image/upload/v1748388674/houseimage6_uv6em9.png",
    featured: true,
    purpose: "Sale",
    type:"Bungalow",
  },
 
   {
    id: 7,
    title: "Infinite Bliss Villa",
    location: "Ishagu, Enugu",
    bedrooms: 5,
    bathrooms: 3,
    price: "₦ 2,350,000,000",
    image: "https://res.cloudinary.com/ds0a0s3k3/image/upload/v1748388673/houseimage7_r3umij.png",
    featured: true,
    purpose: "Sale",
    type:"Bungalow",
  },
  {
    id: 8,
    title: "Luxury Split Villa",
    location: "Work Layout, Owerri",
    bedrooms: 8,
    bathrooms: 6,
    price: "₦ 3,350,000/1 Year",
    image: "https://res.cloudinary.com/ds0a0s3k3/image/upload/v1748388673/houseimage8_en55nk.png",
    featured: true,
    purpose: "Rent",
    type:"Duplex",
  },
  {
    id: 9,
    title: "Family Split Villa",
    location: "Ikeja, Lagos",
    bedrooms: 4,
    bathrooms: 3,
    price: "₦ 600,000,000",
    image: "https://res.cloudinary.com/ds0a0s3k3/image/upload/v1748388673/houseimage9_tmjjmt.png",
    featured: true,
    purpose: "Sale",
    type:"Duplex",
  },

  {
    _id: 10,
    title: "Real Cottage Luxury Villa",
    location: "Victoria Island, Lagos",
    bedrooms: 6,
    bathrooms: 3,
    price: "₦ 3,340,000,000",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792937/House-10_gjljci.avif",
    featured: true,
    purpose: "Sale",
    type:"Duplex",
  },
  {
    _id: 11,
    title: "Split Haven Villa",
    location: "Abeokuta, Ogun",
    bedrooms: 3,
    bathrooms: 2,
    price: "₦ 1,500,000/1 Year",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792939/House-11_vi42vt.avif",
    featured: true,
    purpose: "Rent",
    type:"Duplex",
  },
  {
    _id: 12,
    title: "Luxury Palatial Contemporary",
    location: "FCT, Abuja",
    bedrooms: 7,
    bathrooms: 3,
    price: "₦ 5,350,000,000",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792933/House-12_xqwz28.avif",
    featured: true,
    purpose: "Sale",
    type:"Contemporary",
  },

   {
    _id: 13,
    title: "Senatorial Luxury Villa",
    location: "ikoyi, Lagos",
    bedrooms: 4,
    bathrooms: 3,
    price: "₦ 5,500,000,000",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792940/House-13_zvfupo.avif",
    featured: true,
    purpose: "Sale",
    type:"Contemporary",
  },
  {
    _id: 14,
    title: "Single-Family Villa",
    location: "Victoria Island, Lagos",
    bedrooms: 6,
    bathrooms: 4,
    price: "₦ 350,000,000/1 Year",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792942/House-14_wh5rtw.avif",
    featured: true,
    purpose: "Rent",
    type:"Duplex",
  },
  {
    _id: 15,
    title: "Real Luxury Contemporary",
    location: "Lekki-Ajah, Lagos",
    bedrooms: 5,
    bathrooms: 3,
    price: "₦ 6,200,000,000",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792943/House-15_vcbtli.avif",
    featured: true,
    purpose: "Sale",
    type:"Contemporary",
  },
 
   {
    id: 16,
    title: "Infinite Split Villa",
    location: "Ishagu, Enugu",
    bedrooms: 5,
    bathrooms: 3,
    price: "₦ 2,350,000,000",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792943/House-16_p5jow8.avif",
    featured: true,
    purpose: "Sale",
    type:"Duplex",
  },
  {
    id: 17,
    title: "Luxury Villa",
    location: "Work Layout, Owerri",
    bedrooms: 8,
    bathrooms: 6,
    price: "₦ 3,350,000/1 Year",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792945/House-17_dayuml.avif",
    featured: true,
    purpose: "Rent",
    type:"Duplex",
  },
  {
    id: 18,
    title: "Real Tudor Luxury House",
    location: "Ikeja, Lagos",
    bedrooms: 3,
    bathrooms: 2,
    price: "₦ 600,000,000",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792949/House-18_opu4wd.avif",
    featured: true,
    purpose: "Sale",
    type:"Duplex",
  },
  {
    _id: 19,
    title: "Luxury Contemporary",
    location: "Victoria Island, Lagos",
    bedrooms: 6,
    bathrooms: 3,
    price: "₦ 3,340,000,000",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792948/House-19_sk3ppw.avif",
    featured: true,
    purpose: "Sale",
    type:"Contemporary",
  },
  {
    _id: 20,
    title: "Exquisite Haven House",
    location: "Festac, Lagos",
    bedrooms: 5,
    bathrooms: 3,
    price: "₦ 4,000,000/1 Year",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792948/House-20_jp35tx.avif",
    featured: true,
    purpose: "Rent",
    type:"Contemporary",
  },
  {
    _id: 21,
    title: "Modern Palatial House",
    location: "FCT, Abuja",
    bedrooms: 7,
    bathrooms: 3,
    price: "₦ 2,350,000,000",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792952/House-21_ae7ma0.avif",
    featured: true,
    purpose: "Sale",
    type:"Contemporary",
  },

   {
    _id: 22,
    title: "Tudor Luxury Villa",
    location: "Mushin, Lagos",
    bedrooms: 4,
    bathrooms: 3,
    price: "₦ 4,000,000,000",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792955/House-22_lyremq.avif",
    featured: true,
    purpose: "Sale",
    type:"Duplex",
  },
  {
    _id: 23,
    title: "Real House Luxury Villa",
    location: "Badagry, Lagos",
    bedrooms: 6,
    bathrooms: 4,
    price: "₦ 350,000,000/1 Year",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792954/House-23_u8gkgp.avif",
    featured: true,
    purpose: "Rent",
    type:"Bungalow",
  },
  {
    _id: 24,
    title: "Real Luxury Cottage Villa",
    location: "Lekki-Ajah, Lagos",
    bedrooms: 5,
    bathrooms: 3,
    price: "₦ 7,200,000,000",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792937/House-24_n1qhzq.avif",
    featured: true,
    purpose: "Sale",
    type:"Bungalow",
  },
 
   {
    id: 25,
    title: "Infinite Bliss Duplex",
    location: "Ishagu, Enugu",
    bedrooms: 5,
    bathrooms: 3,
    price: "₦ 2,355,000,000",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792935/House-25_vshnqj.avif",
    featured: true,
    purpose: "Sale",
    type:"Duplex",
  },
  {
    id: 26,
    title: "Single-Family Luxury Villa",
    location: "Work Layout, Owerri",
    bedrooms: 8,
    bathrooms: 6,
    price: "₦ 3,350,000/1 Year",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792937/House-26_rgwyin.avif",
    featured: true,
    purpose: "Rent",
    type:"Bungalow",
  },
  {
    id: 27,
    title: "Split-Level Villa",
    location: "Surulere, Lagos",
    bedrooms: 6,
    bathrooms: 6,
    price: "₦ 600,500,000",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792938/House-27_p4pg90.avif",
    featured: true,
    purpose: "Sale",
    type:"Duplex",
  },
  {
    _id: 28,
    title: "Real Luxury Contemporary",
    location: "Marina, Lagos",
    bedrooms: 6,
    bathrooms: 3,
    price: "₦ 3,340,000,000",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792946/House-28_m0tupm.avif",
    featured: true,
    purpose: "Sale",
    type:"Contemporary",
  },
  {
    _id: 29,
    title: "Exquisite Modern Cottage",
    location: "Akoka, Lagos",
    bedrooms: 5,
    bathrooms: 3,
    price: "₦ 4,000,000/1 Year",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755794932/House-29_faprmx.avif",
    featured: true,
    purpose: "Rent",
    type:"Duplex",
  },
  {
    _id: 30,
    title: "Split Level House",
    location: "Epe, Lagos",
    bedrooms: 7,
    bathrooms: 3,
    price: "₦ 5,350,000,000",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792946/House-30_ncsjqb.avif",
    featured: true,
    purpose: "Sale",
    type:"Bungalow",
  },

   {
    _id: 31,
    title: "Harmony  Villa",
    location: "Mushin, Lagos",
    bedrooms: 4,
    bathrooms: 3,
    price: "₦ 4,000,000,000",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792947/House-31_rgfs2y.avif",
    featured: true,
    purpose: "Sale",
    type:"Bungalow",
  },
  {
    _id: 32,
    title: "Mediterranean Revival  House",
    location: "Victoria Island, Lagos",
    bedrooms: 6,
    bathrooms: 4,
    price: "₦ 350,000,000/1 Year",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792950/House-32_ie660i.avif",
    featured: true,
    purpose: "Rent",
    type:"Duplex",
  },
  {
    _id: 33,
    title: "Tiny  Luxury House",
    location: "FCT, Abuja",
    bedrooms: 5,
    bathrooms: 3,
    price: "₦ 4,200,000,000",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792955/House-33_u4kmgk.avif",
    featured: true,
    purpose: "Sale",
    type:"Duplex",
  },
 
   {
    id: 34,
    title: "Mid-Century Bliss House",
    location: "Ishagu, Enugu",
    bedrooms: 5,
    bathrooms: 3,
    price: "₦ 2,350,000,000",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792955/House-34_vwgent.avif",
    featured: true,
    purpose: "Sale",
    type:"Bungalow",
  },
  {
    id: 35,
    title: "Ranch  Luxury Villa",
    location: "Work Layout, Owerri",
    bedrooms: 8,
    bathrooms: 6,
    price: "₦ 3,350,000/1 Year",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792955/House-35_c5xtk9.avif",
    featured: true,
    purpose: "Rent",
    type:"Bungalow",
  },
  {
    id: 36,
    title: "Real Luxury Cottage",
    location: "Kano, Kano",
    bedrooms: 6,
    bathrooms: 6,
    price: "₦ 600,000,000",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792957/House-36_fynb5r.avif",
    featured: true,
    purpose: "Sale",
    type:"Bungalow",
  },
  {
    _id: 37,
    title: "Modern Luxury House",
    location: "Victoria Island, Lagos",
    bedrooms: 6,
    bathrooms: 3,
    price: "₦ 3,340,000,000",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792955/House-37_vczwgx.avif",
    featured: true,
    purpose: "Sale",
    type:"Contemporary",
  },
  {
    _id: 38,
    title: "Luxury Haven Contemporary",
    location: "Festac, Lagos",
    bedrooms: 5,
    bathrooms: 3,
    price: "₦ 4,000,000/1 Year",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792958/House-38_eldiuw.avif",
    featured: true,
    purpose: "Rent",
    type:"Contemporary",
  },
  {
    _id: 39,
    title: "Tiny Palatial Home",
    location: "Gbagada, Lagos",
    bedrooms: 7,
    bathrooms: 3,
    price: "₦ 5,350,000,000",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792959/House-39_obpran.avif",
    featured: true,
    purpose: "Sale",
    type:"Bungalow",
  },

   {
    _id: 40,
    title: "Harmony Luxury Villa",
    location: "Mushin, Lagos",
    bedrooms: 4,
    bathrooms: 3,
    price: "₦ 4,000,000,000",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792961/House-40_edmfod.avif",
    featured: true,
    purpose: "Sale",
    type:"Bungalow",
  },
  {
    _id: 41,
    title: "Single Family Luxury Villa",
    location: "Victoria Island, Lagos",
    bedrooms: 6,
    bathrooms: 4,
    price: "₦ 350,000,000/1 Year",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792959/House-41_whfxcq.avif",
    featured: true,
    purpose: "Rent",
    type:"Bungalow",
  },
  {
    _id: 42,
    title: "Ranch Villa",
    location: "Lekki-Ajah, Lagos",
    bedrooms: 5,
    bathrooms: 3,
    price: "₦ 4,200,000,000",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792959/House-42_e93fxf.avif",
    featured: true,
    purpose: "Sale",
    type:"Ranch",
  },
 
   {
    id: 43,
    title: "Infinite Bliss Villa",
    location: "Ishagu, Enugu",
    bedrooms: 5,
    bathrooms: 3,
    price: "₦ 2,350,000,000",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792961/House-43_hu2els.avif",
    featured: true,
    purpose: "Sale",
    type:"Bungalow",
  },
  {
    id: 44,
    title: "Real House Luxury Villa",
    location: "Work Layout, Owerri",
    bedrooms: 8,
    bathrooms: 6,
    price: "₦ 3,350,000/1 Year",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792961/House-44_a0ckqs.avif",
    featured: true,
    purpose: "Rent",
    type:"Contemporary",
  },
  {
    id: 45,
    title: "Real House Luxury Villa",
    location: "FCT, Abuja",
    bedrooms: 6,
    bathrooms: 6,
    price: "₦ 600,000,000",
    image: "https://res.cloudinary.com/dofweouvi/image/upload/v1755792961/House-45_mfis52.avif",
    featured: true,
    purpose: "Sale",
    type:"Bungalow",
  },



  


]

export const popularproperties = [

{
    _id: 1,
    title: "Semi Detached Duplex",
    location: "Victoria Island, Lagos",
    bed: 6,
    bath: 3,
    Size: "720sqft",
    price: "₦ 1,430,000,000",
    image: "https://res.cloudinary.com/dcpw3qjmf/image/upload/v1748715120/Link_1_ftewum.png",
    
  },

  {
    _id: 2,
    title: "Special Duplex",
    location: "Victoria Island, Lagos",
    bedrooms: 6,
    bathrooms: 3,
    Size: "720sqft",
    price: "₦ 670,000,000",
    image: "https://res.cloudinary.com/dcpw3qjmf/image/upload/v1748715133/Link_2_iwudhw.png",
    
  },

  {
    _id: 3,
    title: "Split-Level House",
    location: "Victoria Island, Lagos",
    bedrooms: 6,
    bathrooms: 3,
    Size: "720sqft",
    price: "₦ 340,000,000",
    image: "https://res.cloudinary.com/dcpw3qjmf/image/upload/v1748715150/Link_3_buiahj.png",
    
  },

  {
    _id: 4,
    title: "Twin Duplex",
    location: "Victoria Island, Lagos",
    bedrooms: 6,
    bathrooms: 3,
    Size: "720sqft",
    price: "₦ 290,000,000",
    image: "https://res.cloudinary.com/dcpw3qjmf/image/upload/v1748715155/Link_4_sjsnvf.png",
    
  },
  {
    _id: 5,
    title: "Semi Detached Duplex",
    location: "Victoria Island, Lagos",
    bed: 6,
    bath: 3,
    Size: "720sqft",
    price: "₦ 1,430,000,000",
    image: "https://res.cloudinary.com/dcpw3qjmf/image/upload/v1748715120/Link_1_ftewum.png",
    
  },

  {
    _id: 6,
    title: "Special Duplex",
    location: "Victoria Island, Lagos",
    bedrooms: 6,
    bathrooms: 3,
    Size: "720sqft",
    price: "₦ 670,000,000",
    image: "https://res.cloudinary.com/dcpw3qjmf/image/upload/v1748715133/Link_2_iwudhw.png",
    
  },

  {
    _id: 7,
    title: "Split-Level House",
    location: "Victoria Island, Lagos",
    bedrooms: 6,
    bathrooms: 3,
    Size: "720sqft",
    price: "₦ 340,000,000",
    image: "https://res.cloudinary.com/dcpw3qjmf/image/upload/v1748715150/Link_3_buiahj.png",
    
  }


]